# Generated by Django 3.2 on 2021-05-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
